### ISSUE TITLE
Private Room's messages can seen by anyone easily.

### ISSUE THREAD

**Issue by OyuNet** [K9Crypt/website#2]
I recently created room to test the entire service. But the problem is when user (in that case that's me) creates a specifically "private" room, any user who has the room id can see the actual text messages. They just can't send a new message to system because they don't have a password. And that situation is antipodes of the private meaning in my opinion.

So we need to require a password the messages, otherwise anyone can see the private messages. 

<img width="1512" alt="Ekran Resmi 2024-08-30 22 40 38" src="https://github.com/user-attachments/assets/64daff4d-3af2-487d-854c-d8b14bca3b7b">

And I created this room with my browser. You can see the results in the upper image.

Then I am going to enter the same URL (https://k9crypt.xyz/room/BCZCBKX2OJ8ZL1LF2X6A) with another browser. (w/ Chrome)

<img width="1512" alt="Ekran Resmi 2024-08-30 22 47 05" src="https://github.com/user-attachments/assets/de46d9b5-feb8-4df1-ba7c-73bf24045e2d">

Finally, as you can see, anyone who can predict the room id or who makes brute force, it really doesn't matter, can see the actual messages easily.

<img width="1512" alt="Ekran Resmi 2024-08-30 22 48 52" src="https://github.com/user-attachments/assets/c793a021-40ba-433b-8b7c-9acaae9372ab">

This happens when not authorized user tries to send message.

**Comment by Queaxtra** [comment]
First of all, thank you for the error, we fixed it. Now, when users enter private rooms (encrypted rooms), if they have set a username, and yes, usernames are kept in the local database, so you only need to select it once, they can directly enter the room password and join the chat. For public rooms, of course, this does not apply.
